# Generated by Django 2.0 on 2017-12-21 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaning_logs', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='owner',
            field=models.ForeignKey(default=1, on_delete='on_delete=models.CASCADE', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
